#Name='CBAM_edge'
#net='cganet.CBAM_UNet'
#Name='UNnet'
#net='unet.U_Net'
#Name='CGAM_SUM_EDGE'
#net='cganet.CGAM_UNet2'
#Name='CBAM'
#net='cganet.CBAM_UNet'
#Name='CGAM_SUM'
Name='CGAM_hard'
net='cganet.CGAM_UNet2'
Image_size = (544, 544)
#ROOT = './dataset/CHASEDB'
#weight_root="/home/changwei/ISBI_drive/drive/weights_CHASEDB/"
#Hard_ROOT="/home/changwei/ISBI_drive/drive/dataset/CHASEDB/argtraining/"
ROOT = './dataset/Drive'
weight_root= '/home/changwei/ISBI_drive/drive/weights/'
Hard_ROOT='/home/changwei/ISBI_drive/drive/dataset/DRIVE/argtraining'
dataset='CHASEDB'
BATCHSIZE_PER_CARD = 3
INITAL_EPOCH_LOSS = 10000
NUM_EARLY_STOP = 20
NUM_UPDATE_LR = 10
GPU_id = '0,1'
BINARY_CLASS = 1
edge=True
edge_loss_weight=1
maintain_epoch=300 #of iter at starting learning rate
decay_epoch=300 #of iter to linearly decay learning rate to zero
TOTAL_EPOCH = maintain_epoch+decay_epoch
epoch_count=1
Argument_start=200
Argument_epoch=100

